### ISSUE TITLE
Change name to press-materials

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/outreach-materials#4]
I think that press-materials is a more easy to remember name.

**Comment by npch** [comment]
Would this be solved by adding extra description into the readme?

I'm reluctant to change to press-materials as we're not expecting them to be used by journalists, but by Institute collaborators.

**Comment by rgaiacs** [comment]
> Would this be solved by adding extra description into the readme?

Can we pin the repository? https://github.com/blog/2191-pin-repositories-to-your-github-profile

> I'm reluctant to change to press-materials as we're not expecting them to be used by journalists, but by Institute collaborators.

Fair enough!

**Comment by npch** [comment]
> Can we pin the repository? https://github.com/blog/2191-pin-repositories-to-your-github-profile

That sounds like a great solution - done! (along with pinning the "useful-references" and "website" repos.
