### ISSUE TITLE
Update numbers

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/outreach-materials#7]
- [x] +4500 Twitter followers
- [x] 20,000 visits per month

**Comment by rgaiacs** [comment]
The numbers on the description are out of date.

**Comment by selina-aragon** [comment]
What outreach materials are you referring to? Is it the flyer? I'm aiming to update both this week.

**Comment by rgaiacs** [comment]
> What outreach materials are you referring to?

https://github.com/softwaresaved/outreach-materials/blob/master/presentations/SSI%20Introduction.pdf

**Comment by selina-aragon** [comment]
@rgaiacs I don't have access to those slides (I don't think). @npch where can I find the slides to update them? 
Note that our Twitter followers are now over 6K.

**Comment by npch** [comment]
I've sent the original slides to @selina-aragon to update and then upload to GitHub. It should be okay to put up the PPTX version as well.

**Comment by selina-aragon** [comment]
Have updated the numbers. I've created a pull request for Neil to review. 
Closing issue.
